version: '3.8'

services:
  app:
    build: .
    container_name: backend
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/mydatabase?authSource=admin&retryWrites=true&w=majority
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase

    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ./frontend/fire-base-hosting-react-app
      args:
        - REACT_APP_API_URL=http://localhost:8000
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://app:8000
    ports:
      - "3000:80"
      
volumes:
  mongo-data:
